/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.x.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as auth from "../auth.js";
import type * as backups from "../backups.js";
import type * as email from "../email.js";
import type * as files from "../files.js";
import type * as lib from "../lib.js";
import type * as migrate from "../migrate.js";
import type * as moodboard from "../moodboard.js";
import type * as plan from "../plan.js";
import type * as posts from "../posts.js";
import type * as settings from "../settings.js";
import type * as versions from "../versions.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  auth: typeof auth;
  backups: typeof backups;
  email: typeof email;
  files: typeof files;
  lib: typeof lib;
  migrate: typeof migrate;
  moodboard: typeof moodboard;
  plan: typeof plan;
  posts: typeof posts;
  settings: typeof settings;
  versions: typeof versions;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
